services:
  app:
    build: .
    container_name: go_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123   # root password
      MYSQL_DATABASE: ecom               # auto create database
      MYSQL_USER: appuser                # ✅ don't use root here
      MYSQL_PASSWORD: appsecret          # password for appuser
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
